version: '3'
services:
        php-apache:
                build:
                        context: ./php-apache
                ports:
                        - 80:80
                volumes:
                        - ./html:/var/www/html